import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Multi Tac API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="https://multi-tac.netlify.app">Multi Tac API Server!</a>
        </h1>

        <p className={styles.description}>
          The API in{" "}
          <code className={styles.code}>
            https://mt-server.netlify.app/api/
          </code>{" "}
          is designed in NextJS & used NotionAPI as Database.
        </p>

        <div className={styles.grid}>
          <a href="https://multi-tac.netlify.app" className={styles.card}>
            <h2>Multi Tac &rarr;</h2>
            <p>Play the Realtime Multiplayer Tic Tac Toe Game!</p>
          </a>
          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Author &rarr;</h2>
            <p>Discover and Know More about the Author of Multi-Tac.</p>
          </a>

          <a href="https://github.com/tam11a/multi-tac" className={styles.card}>
            <h2>Github #1 &rarr;</h2>
            <p>The Prograssive Web App Code in ReactJS is Now in Github!</p>
          </a>

          <a href="https://github.com/tam11a/multi-tac" className={styles.card}>
            <h2>Github #2 &rarr;</h2>
            <p>
              The Backend Application Code in NextJS is Opensource in Github!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
